### ISSUE TITLE
Invidio.us instance cannot be used as a YouTube proxy anymore

### ISSUE THREAD

**Issue by Zambito1** [Phate6660/rsPhate#1]
https://github.com/Phate6660/rsPhate/blob/70b52e028a8b1e425f9a14bd8b83e541a951e4ee/src/functions/yt_tw_check.rs#L21

The invidio.us site shut down, and now is only used to list other public instances. I personally have used invidiou.site, yewtu.be, and invidious.xyz. It looks like the last one has been having some issues lately, so I recommend changing the link to one of the first two.

**Comment by Phate6660** [comment]
Yeah, I still need to update that. When I have time to get to it, I figured I'd add a note about the shutdown of the main instance and give a small list of other instances that I've personally tried.

**Comment by Phate6660** [comment]
Invidio instances have been very rocky. I've removed the youtube check, at least until something better comes along (e.g. invidio starts being actively developed again or a good alternative emerges).

Until then, I'll be closing this issue for now.
